// EVENT SLIDER REQUEST
const EVENT_SLIDER_SUCCESS = 'EVENT_SLIDER_SUCCESS'
const EVENT_SLIDER_FAILURE = 'EVENT_SLIDER_FAILURE'
const EVENT_SLIDER_REQUEST = 'EVENT_SLIDER_REQUEST'

export { EVENT_SLIDER_SUCCESS, EVENT_SLIDER_FAILURE, EVENT_SLIDER_REQUEST }
