stages:
- precache
- lint
- test
language: node_js
node_js: '9'
addons:
  apt:
    packages:
    - libnotify-bin
install: true
before_script: npm install -g npm@5.8.0
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
  - "~/.npm"
jobs:
  include:
  - stage: test
    install: &1
    - npm install
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: &2
      directories:
      - "~/.npm"
      - node_modules
  - stage: test
    install: *1
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: *2
    node_js: '8'
  - stage: test
    install: *1
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: *2
    node_js: '10'
  - stage: lint
    before_install: true
    install:
    - npm install -g eslint
    - npm install -g snazzy
    script: npm run lint
  - stage: precache
    script: true
after_success: npm run coverage
sudo: false
before_deploy:
- rm -rf node_modules
deploy:
  provider: heroku
  local_dir: build
  api_key:
    secure: GA0Gw5A3XcCm7JkFi21VqAqxGXkl5QWrRPOSzY/IQl5ya/PBGQ+ZQld5pwTKkO7bzSeUvJNoyf4NM3hErPR4nGQhFyyCMSuhJ/lD+SaUOs+pZOq6UhGro1CHB7+q5Vww9kd7h/oCQdLca0+ZNkyWV1G3C4yax6FntG3VNh76O/55GMucLF3Xo4u/yx2UXyKMKV+sAtuZL/GwbQuytq9WFrtCrr1Wjxn6ub6IeTdybMCIIwaompzLYVfNXIjK6b6VAZiHUcmoudAwR+oDQYiBc4TjpScqwrVbLLLhEeNL4C6xRuBtMdVUznLcysdbnKze42TgUuW3tvv3ZNgtKwLJw6xuicWPZfYOnqGKcySgsMDiEjAWlFKI1uImddOd43Xdu80csQ61WtNVRfoXZOCOI7GRibUe+arNYE53UzWrbytu0XgDjdfjlC4B432Mq8Dl9bFkmPr3zU03TMw0ggDd+0/s7Sesyqpcol0qtVR0Cvq8wWH+/HcLHAhloZn9NqgaFrQpELEnGPeBPJX+Z7tydZRY2WvXt0DzhX/tFhfH3nioABezbFVwpiHVEHXPCB7Jc0Y7B1N1XJAx5inBthZBQdUCD/EFCTkf3sKvypPBBoDHvPFzetLoRgzdf49zNUmKAv5WyYsWbp7IfgwSSs88QyhxfF0/rPEx+AY/VSLsGIQ=
  app: react-seed-starter
  on: master
  skip_cleanup: true
notifications:
  webhooks: https://hooks.slack.com/services/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
