stages:
  - precache
  - lint
  - test
language: node_js
node_js: '9'
addons:
  apt:
    packages:
      - libnotify-bin
install: true
before_script: npm install -g npm@5.8.0
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
    - '~/.npm'
jobs:
  include:
    - stage: test
      install: &1
        - npm install
      script: npm run test
      before_install: true
      after_success: npm run coverage
      cache: &2
        directories:
          - '~/.npm'
          - node_modules
    - stage: test
      install: *1
      script: npm run test
      before_install: true
      after_success: npm run coverage
      cache: *2
      node_js: '8'
    - stage: test
      install: *1
      script: npm run test
      before_install: true
      after_success: npm run coverage
      cache: *2
      node_js: '10'
    - stage: lint
      before_install: true
      install:
        - npm install -g eslint
        - npm install -g snazzy
      script: npm run lint
    - stage: precache
      script: true
after_success: npm run coverage
sudo: false
before_deploy:
  - rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: lv1fXka1cYwpQ576NQjD5aIFnKe3r1detXS57BdXThID75Ttem9pYONQPvWohOT8cpNxsn/g9xSuplGBDWRKB+MThTmWIyo7EAAkFKlfG0aFm/7nytnu+EYpkY+rXip4/HtL33JMBFM8CggDK65HwXvSMkmkHX82PAbSnSjt1pTxkn070vxA+RPMsYEeHam13Am33E4hBFCaooCfsVFriSsZCn3qddibaoBOSGkRSk3SkaKDfz7/Yj0zyheWnPf+XQmZ52aQy4POKAinYLnQrSp/bD7tnVRCUsybyuXg5zDToU5N2NNtQdyzbGPLjW/yaJBPkbB+0cyZnFB2XSMkPaoWu/NDRcj0P4O+aDMahUFCZGadn2zDLAwsvZ7sdDJ3GDUJLn2QUpCDCYaZi0d4NWEKrBUw+NCfxrpM9GCK9Vdr3kU1D2WHRvbQraDZs7S7LakngHETRnncddAEobSR27FMQ7vdKFBLl70NXBfqnbqO+TZiMe7MBXQqxW2w5klWYSzAKea4Do4rKjs1k9i+LCNn7Gr87Ocl2YUHtgiUoLs8xdSzEcR0KsZH2dPeegNp5l0uKSyFX5UGm0YAc6kxdRJi7e2ULyR2MpR0TWkQyshKjs9s0EIdumssjAoTByNOJ5ukmuBrmwnNZeEUjP+Nh7VD/giwHHlHsfcEkGmIuiU=
  app: react-seed
  on: master
  skip_cleanup: true
notifications:
  webhooks: https://hooks.slack.com/services/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
