export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST'
export const EVENT_CREATE_FAILURE = 'EVENT_CREATE_FAILURE'
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS'

export const EVENT_CREATE_CHANGE = 'EVENT_CREATE_CHANGE'
export const EVENT_CREATE_CLEAR_ERROR = 'EVENT_CREATE_CLEAR_ERROR'
export const EVENT_CREATE_CLEAR = 'EVENT_CREATE_CLEAR'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAILURE = 'EVENT_DELETE_FAILURE'
