// EVENT REQUEST

const EVENT_SUCCESS = 'EVENT_SUCCESS'
const EVENT_FAILURE = 'EVENT_FAILURE'
const EVENT_REQUEST = 'EVENT_REQUEST'

// EVENT SEARCH HANDLE

const EVENT_SEARCH = 'SEARCH_EVENT'
// EVENT ERROR HANDLE

const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export {
  EVENT_SUCCESS,
  EVENT_FAILURE,
  EVENT_REQUEST,
  RESET_ERROR_MESSAGE,
  EVENT_SEARCH
}
