// EVENT REQUEST
const EVENT_MEMBER_SUCCESS = 'EVENT_MEMBER_SUCCESS'
const EVENT_MEMBER_FAILURE = 'EVENT_MEMBER_FAILURE'
const EVENT_MEMBER_REQUEST = 'EVENT_MEMBER_REQUEST'

// EVENT SEARCH HANDLE

const EVENT_MEMBER_SEARCH = 'SEARCH_MEMBER_EVENT'
// EVENT ERROR HANDLE

const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export {
  EVENT_MEMBER_SUCCESS,
  EVENT_MEMBER_FAILURE,
  EVENT_MEMBER_REQUEST,
  RESET_ERROR_MESSAGE,
  EVENT_MEMBER_SEARCH
}
